apiVersion: apps/v1
kind: Deployment
metadata:
  name: __APPLICATION__
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: __APPLICATION__
          args:
            - server
          ports:
            - containerPort: __APPLICATION_PORT__
          resources:
            limits:
              cpu: 1.0
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 256Mi
          env:
            - name: RUST_LOG
              value: "bridge_dao_indexer=debug,dexpa=debug,warp=debug,ton-consumer=debug"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-credentials
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@127.0.0.1:5432/bridge_dao_indexer"
            - name: DB_POOL_SIZE
              value: "5"
            - name: KAFKA_USER
              valueFrom:
                secretKeyRef:
                  name: ton-kafka-credentials
                  key: ton_kafka_user
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ton-kafka-credentials
                  key: ton_kafka_password
            - name: STATES_RPC_ENDPOINT
              value: "http://35.240.13.113:8081"
            - name: KAFKA_GROUP_ID
              value: "ton-bridge-dao-indexer-test-1"
            - name: KAFKA_CLIENT_ID
              value: "ton-bridge-dao-indexer-test-client"
            - name: DAO_ROOT
              value: "0:6da8defd136c0227dfa24edde79728142d2bfb74bc9edf66ad86ae7cd8e56a86"
