include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "templates/deploy.gitlab-ci.yaml"

stages:
  - cloudbuild
  - deploy

cloudbuild:image:prod:
  only:
    - prod
  except:
    - tags
  extends: .cloudbuild:common

deploy:prod:
  only:
    - prod
  except:
    - tags
  extends: .deploy
  environment:
    name: prod

stop:prod:
  only:
    - prod
  except:
    - tags
  extends: .stop
  environment:
    name: prod
