include:
  - project: 'common/gitlab-ci'
    ref: master
    file: '/templates/deploy.gitlab-ci.yaml'

deploy:config-everdao:
  extends: .deploy:configuration
  variables:
    CONFIG_GROUP: "broxus"
    CONFIG_APPLICATION: $CI_PROJECT_NAME-everdao
    CONFIG_APPLICATION_PORT: "9000"
    CONFIG_HEALTHZ_PORT: "9001"
    CONFIG_HEALTHZ_TYPE: "tcpSocket"
  before_script:
    - mkdir deploy
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dexpa.io/common/kustomize.git deploy/common
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dexpa.io/broxus/trading/infrastructure.git deploy/broxus
  only:
    - prod
  except:
    - tags
  tags:
    - rust
  artifacts:
    name: $CI_COMMIT_REF_NAME-deploy-everdao-indexer-prod-config
    paths:
      - deploy/deployment.yaml
  script:
    - |
      deploy/common/build.sh kustomize \
      -t statefulset \
      -r deploy/common/base/service-statefulset.yaml \
      -r kustomize/service-http-expose.everdao.prod.yaml \
      -p deploy/broxus/kustomize/env.prod.yaml \
      -p kustomize/overrides.everdao.prod.yaml \
      -c deploy/broxus/config/kafka-settings.prod.json \
      > kustomization.yaml

deploy:rollout-everdao:
  extends: .deploy:rollout
  when: manual
  variables:
    CLUSTER_SETUP: $CLUSTER_SETUP_PROD
    CONFIG_APPLICATION: $CI_PROJECT_NAME-everdao
  only:
    - prod
  except:
    - tags
  tags:
    - rust
  dependencies:
    - deploy:config-everdao
  environment:
    name: $CI_PROJECT_NAME-everdao
    on_stop: deploy:stop-everdao

deploy:stop-everdao:
  extends: .deploy:stop
  variables:
    CLUSTER_SETUP: $CLUSTER_SETUP_PROD
    CONFIG_APPLICATION: $CI_PROJECT_NAME-everdao
  only:
    - prod
  except:
    - tags
  tags:
    - rust
  environment:
    name: $CI_PROJECT_NAME-everdao
    action: stop
